name: build-pdf
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: src/cv.tex
      - uses: actions/upload-artifact@v2
        with:
          name: pdf
          path: cv.pdf
